In [2]:
import pandas as pd
import numpy as np

## Load the Dataset

In [3]:
df = pd.read_csv("../data/raw/dataset.csv")

/var/folders/q2/dqn4llld38d02_v51ydg29yw0000gn/T/ipykernel_15027/2432386781.py:1: DtypeWarning: Columns (0: C02970V03592) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/dataset.csv")

In [4]:
df.head()

,STATISTIC,Statistic Label,TLIST(A1),Year,C02970V03592,Number of Bedrooms,C02969V03591,Property Type,C03004V03625,Location,UNIT,VALUE
0,RIA02,RTB Average Monthly Rent Report,2008,2008,-,All bedrooms,-,All property types,110000,Carlow,Euro,748.48
1,RIA02,RTB Average Monthly Rent Report,2008,2008,-,All bedrooms,-,All property types,110200,Carlow Town,Euro,811.53
2,RIA02,RTB Average Monthly Rent Report,2008,2008,-,All bedrooms,-,All property types,110300,"Graiguecullen, Carlow",Euro,711.35
3,RIA02,RTB Average Monthly Rent Report,2008,2008,-,All bedrooms,-,All property types,110500,"Tullow, Carlow",Euro,720.04
4,RIA02,RTB Average Monthly Rent Report,2008,2008,-,All bedrooms,-,All property types,110550,Cavan,Euro,571.72

## Explore the Dataset

In [5]:
print("Rows and columns:")
print(df.shape)

Rows and columns:
(337176, 12)

In [6]:
df.columns.tolist()

['STATISTIC',
 'Statistic Label',
 'TLIST(A1)',
 'Year',
 'C02970V03592',
 'Number of Bedrooms',
 'C02969V03591',
 'Property Type',
 'C03004V03625',
 'Location',
 'UNIT',
 'VALUE']

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 337176 entries, 0 to 337175
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   STATISTIC           337176 non-null  str
 1   Statistic Label     337176 non-null  str
 2   TLIST(A1)           337176 non-null  int64
 3   Year                337176 non-null  int64
 4   C02970V03592        337176 non-null  object
 5   Number of Bedrooms  337176 non-null  str
 6   C02969V03591        337176 non-null  str
 7   Property Type       337176 non-null  str
 8   C03004V03625        337176 non-null  int64
 9   Location            337176 non-null  str
 10  UNIT                337176 non-null  str
 11  VALUE               113679 non-null  float64
dtypes: float64(1), int64(3), object(1), str(7)
memory usage: 30.9+ MB

In [8]:
df.isnull().sum()

STATISTIC                  0
Statistic Label            0
TLIST(A1)                  0
Year                       0
C02970V03592               0
Number of Bedrooms         0
C02969V03591               0
Property Type              0
C03004V03625               0
Location                   0
UNIT                       0
VALUE                 223497
dtype: int64

In [9]:
df.head(10)

,STATISTIC,Statistic Label,TLIST(A1),Year,C02970V03592,Number of Bedrooms,C02969V03591,Property Type,C03004V03625,Location,UNIT,VALUE
0,RIA02,RTB Average Monthly Rent Report,2008,2008,-,All bedrooms,-,All property types,110000,Carlow,Euro,748.48
1,RIA02,RTB Average Monthly Rent Report,2008,2008,-,All bedrooms,-,All property types,110200,Carlow Town,Euro,811.53
2,RIA02,RTB Average Monthly Rent Report,2008,2008,-,All bedrooms,-,All property types,110300,"Graiguecullen, Carlow",Euro,711.35
3,RIA02,RTB Average Monthly Rent Report,2008,2008,-,All bedrooms,-,All property types,110500,"Tullow, Carlow",Euro,720.04
4,RIA02,RTB Average Monthly Rent Report,2008,2008,-,All bedrooms,-,All property types,110550,Cavan,Euro,571.72
5,RIA02,RTB Average Monthly Rent Report,2008,2008,-,All bedrooms,-,All property types,111100,Cavan Town,Euro,598.44
6,RIA02,RTB Average Monthly Rent Report,2008,2008,-,All bedrooms,-,All property types,110600,"Bailieborough, Cavan",Euro,NaN
7,RIA02,RTB Average Monthly Rent Report,2008,2008,-,All bedrooms,-,All property types,110800,"Ballyconnell, Cavan",Euro,598.74
8,RIA02,RTB Average Monthly Rent Report,2008,2008,-,All bedrooms,-,All property types,110900,"Ballyjamesduff, Cavan",Euro,598.45
9,RIA02,RTB Average Monthly Rent Report,2008,2008,-,All bedrooms,-,All property types,111000,"Belturbet, Cavan",Euro,481.83

In [11]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 337176
Columns: 12

In [12]:
for col in df.columns:
    print(col)

STATISTIC
Statistic Label
TLIST(A1)
Year
C02970V03592
Number of Bedrooms
C02969V03591
Property Type
C03004V03625
Location
UNIT
VALUE

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 337176 entries, 0 to 337175
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   STATISTIC           337176 non-null  str
 1   Statistic Label     337176 non-null  str
 2   TLIST(A1)           337176 non-null  int64
 3   Year                337176 non-null  int64
 4   C02970V03592        337176 non-null  object
 5   Number of Bedrooms  337176 non-null  str
 6   C02969V03591        337176 non-null  str
 7   Property Type       337176 non-null  str
 8   C03004V03625        337176 non-null  int64
 9   Location            337176 non-null  str
 10  UNIT                337176 non-null  str
 11  VALUE               113679 non-null  float64
dtypes: float64(1), int64(3), object(1), str(7)
memory usage: 30.9+ MB

In [14]:
df.isnull().sum()

STATISTIC                  0
Statistic Label            0
TLIST(A1)                  0
Year                       0
C02970V03592               0
Number of Bedrooms         0
C02969V03591               0
Property Type              0
C03004V03625               0
Location                   0
UNIT                       0
VALUE                 223497
dtype: int64

In [15]:
print(df["Property Type"].unique())

<StringArray>
[ 'All property types',      'Detached house', 'Semi detached house',
       'Terrace house',           'Apartment',         'Other flats']
Length: 6, dtype: str

In [16]:
print(df["Number of Bedrooms"].unique())

<StringArray>
[ 'All bedrooms',       'One bed',       'Two bed',     'Three bed',
    '1 to 2 bed',    '1 to 3 bed', 'Four plus bed']
Length: 7, dtype: str

In [17]:
print(df["Year"].unique())

[2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021
 2022 2023 2024 2025]

In [18]:
df["VALUE"].describe()

count    113679.000000
mean       1039.743521
std         495.442489
min         233.670000
25%         659.745000
50%         936.500000
75%        1291.400000
max        6385.740000
Name: VALUE, dtype: float64

## Data Cleaning

In [19]:


rent_df = df[[
    "Location",
    "Property Type",
    "Number of Bedrooms",
    "Year",
    "VALUE"
]]

In [20]:
rent_df.head()

                Location       Property Type Number of Bedrooms  Year   VALUE
0                 Carlow  All property types       All bedrooms  2008  748.48
1            Carlow Town  All property types       All bedrooms  2008  811.53
2  Graiguecullen, Carlow  All property types       All bedrooms  2008  711.35
3         Tullow, Carlow  All property types       All bedrooms  2008  720.04
4                  Cavan  All property types       All bedrooms  2008  571.72

In [21]:
rent_df = rent_df.dropna()

In [22]:
rent_df.info()

<class 'pandas.DataFrame'>
Index: 113679 entries, 0 to 336591
Data columns (total 5 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Location            113679 non-null  str
 1   Property Type       113679 non-null  str
 2   Number of Bedrooms  113679 non-null  str
 3   Year                113679 non-null  int64
 4   VALUE               113679 non-null  float64
dtypes: float64(1), int64(1), str(3)
memory usage: 5.2 MB

In [23]:
rent_df.isnull().sum()

Location              0
Property Type         0
Number of Bedrooms    0
Year                  0
VALUE                 0
dtype: int64

In [24]:
rent_df.head(10)

                 Location       Property Type Number of Bedrooms  Year   VALUE
0                  Carlow  All property types       All bedrooms  2008  748.48
1             Carlow Town  All property types       All bedrooms  2008  811.53
2   Graiguecullen, Carlow  All property types       All bedrooms  2008  711.35
3          Tullow, Carlow  All property types       All bedrooms  2008  720.04
4                   Cavan  All property types       All bedrooms  2008  571.72
5              Cavan Town  All property types       All bedrooms  2008  598.44
7     Ballyconnell, Cavan  All property types       All bedrooms  2008  598.74
8   Ballyjamesduff, Cavan  All property types       All bedrooms  2008  598.45
9        Belturbet, Cavan  All property types       All bedrooms  2008  481.83
10       Cootehill, Cavan  All property types       All bedrooms  2008  529.43

## Save Cleaned Dataset

In [25]:
rent_df.to_csv("../data/processed/rentwise_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

## Prepare Data for Machine Learning

In [26]:
# Load the cleaned dataset
rent_df = pd.read_csv("../data/processed/rentwise_cleaned.csv")

rent_df.head()

                Location       Property Type Number of Bedrooms  Year   VALUE
0                 Carlow  All property types       All bedrooms  2008  748.48
1            Carlow Town  All property types       All bedrooms  2008  811.53
2  Graiguecullen, Carlow  All property types       All bedrooms  2008  711.35
3         Tullow, Carlow  All property types       All bedrooms  2008  720.04
4                  Cavan  All property types       All bedrooms  2008  571.72

In [27]:
X = rent_df.drop("VALUE", axis=1)
y = rent_df["VALUE"]

print(X.head())
print(y.head())

                Location       Property Type Number of Bedrooms  Year
0                 Carlow  All property types       All bedrooms  2008
1            Carlow Town  All property types       All bedrooms  2008
2  Graiguecullen, Carlow  All property types       All bedrooms  2008
3         Tullow, Carlow  All property types       All bedrooms  2008
4                  Cavan  All property types       All bedrooms  2008
0    748.48
1    811.53
2    711.35
3    720.04
4    571.72
Name: VALUE, dtype: float64

In [28]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [29]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [32]:
rent_df = pd.read_csv("../data/processed/rentwise_cleaned.csv")

In [33]:
X = rent_df.drop("VALUE", axis=1)
y = rent_df["VALUE"]

In [34]:
categorical_features = [
    "Location",
    "Property Type",
    "Number of Bedrooms"
]

In [35]:
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ],
    remainder="passthrough"
)

## Split the Dataset

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [38]:
print("Training set:", X_train.shape)
print("Testing set:", X_test.shape)

Training set: (90943, 4)
Testing set: (22736, 4)

In [39]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline

In [40]:
model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor(
        n_estimators=100,
        random_state=42,
        n_jobs=-1
    ))
])

## Train the Model

In [41]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Location', 'Property Type',
                                                   'Number of Bedrooms'])])),
                ('regressor',
                 RandomForestRegressor(n_jobs=-1, random_state=42))])

In [42]:
predictions = model.predict(X_test)

In [43]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [44]:
mae = mean_absolute_error(y_test, predictions)
rmse = mean_squared_error(y_test, predictions) ** 0.5
r2 = r2_score(y_test, predictions)

print(f"MAE: €{mae:.2f}")
print(f"RMSE: €{rmse:.2f}")
print(f"R² Score: {r2:.3f}")

MAE: €60.83
RMSE: €110.58
R² Score: 0.949

In [45]:
results = X_test.copy()

results["Actual Rent"] = y_test.values
results["Predicted Rent"] = predictions

results.head(10)

,Location,Property Type,Number of Bedrooms,Year,Actual Rent,Predicted Rent
92798,Cork City,Terrace house,Three bed,2021,1331.11,1351.9411
50041,Waterford City,Semi detached house,Two bed,2015,492.01,525.8550
89965,"Salthill, Galway",All property types,All bedrooms,2021,1223.66,1206.8893
37001,"Tullamore, Offaly",Terrace house,Three bed,2013,565.79,566.3711
54060,Kilkenny,Other flats,1 to 3 bed,2015,452.17,518.1838
78776,Monaghan,Terrace house,Two bed,2019,609.07,650.2801
96265,"Ongar, Dublin 15",Terrace house,All bedrooms,2022,1712.67,1595.3737
106255,"Youghal, Cork",Apartment,All bedrooms,2024,976.66,976.0207
19687,"Castletroy, Limerick",All property types,All bedrooms,2011,694.70,748.1345
61180,Tipperary Town,Apartment,1 to 3 bed,2016,446.26,504.1809

## Save Trained Model

In [46]:
import joblib

joblib.dump(model, "../models/rentwise_model.pkl")

print("Model saved successfully!")

Model saved successfully!